name: Run PHP CodeSniffer

# Run PHPCBF to fix changes then annotate PHPCS
# NB: Pull requests from forks do not have access to repository secrets so cannot commit changes.

on:
  push:
    branches:
      - master

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        php: [ '7.4' ]

    steps:

      - name: Run PHPCBF to fix what it can
        continue-on-error: true
        run: vendor/bin/phpcbf

      - name: Run PHPCS to add annotations to the code
        id: run-phpcs
        continue-on-error: true
        run: vendor/bin/phpcs -q -n --report=checkstyle | cs2pr

      - name: Discard environment changes before commiting other changes
        run: git checkout -- .env.testing

      - name: Check success
        if: steps.run-phpcs.outcome == 'success'
        run: curl -o .github/phpcs.svg https://img.shields.io/badge/PHPCS-WPCS%20${{ steps.phpstan-level.outputs.level}}-8892BF.svg

      - name: Check failures
        if: steps.run-phpcs.outcome != 'success'
        run: curl -o .github/phpcs.svg https://img.shields.io/badge/PHPCS-WPCS%20${{ steps.phpstan-level.outputs.level}}❌-lightgrey.svg

      - name: Git pull in case chanages were committed in another Action
        run: git pull

      - name: Commit PHPCBF changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 PHPCBF"

